 
version: 2.1
jobs:
  compile:
   docker:
      - image: bryanhafidz/bryan-docker:0x02
   steps:
      - run:
          command: |
           apt-get -y update && apt-get -y upgrade && apt-get -y install git-core
           git config --global user.name "MumetNgoding"
           git config --global user.email "nugroho31.com@gmail.com"
           mkdir ReloadedOs
           cd ReloadedOs
workflows:
  version: 2.1 
  cooking:
    jobs:
      - compile
