version: 2.1
jobs:
  compile:
   docker:
      - image: ubuntu:20.04
   steps:
      - run:
          command: |
           apt-get -y update && apt-get -y upgrade && apt-get -y install curl libstdc++6 git wget python-is-python3 gcc clang 
           git config --global user.name "MumetNgoding"
           git config --global user.email "nugroho31.com@gmail.com"
           cd Q
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile